[package]
edition = "2021"
name = "cfmm-contracts"
version = "0.0.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = {version = "0.17", features = ["abigen"]}
