[package]
name = "cfmm-contracts"
version = "0.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = { version="0.17.*", features = ["abigen"] }
serde_json = "1.0.79"

