[profile.default]
libs = ["node_modules"]
optmitizer = false
out = "out"
remappings = [
    "ds-test/=node_modules/ds-test/src/",
    "forge-std/=node_modules/forge-std/src/",
    "@openzeppelin/=node_modules/openzeppelin-solidity/contracts/",
]
solc_version = "0.8.17"
src = "src"

[profile.ci]
fuzz_runs = 5000

[profile.deploy]
optmitizer = true
optmitizer-runs = 10_000_000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
