[profile.default]
libs = ["lib"]
optmitizer = false
out = "out"
solc_version = "0.8.17"
src = "src"

[profile.ci]
fuzz_runs = 5000

[profile.deploy]
optmitizer = true
optmitizer-runs = 10_000_000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
